# Generated by Django 5.0.1 on 2024-01-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='UniqueComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('number', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Номер п/п')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('decimal_number', models.CharField(max_length=10, unique=True, verbose_name='Децимальный номер')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('developed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee', verbose_name='Разработал')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Плата',
                'verbose_name_plural': 'Платы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ModuleComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_quantity', models.IntegerField(default=1, verbose_name='Необходимое количество')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.module', verbose_name='Модуль')),
                ('pcb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pcb', verbose_name='Печатная плата')),
            ],
            options={
                'verbose_name': 'Состав модуля',
                'verbose_name_plural': 'Составы модулей',
            },
        ),
        migrations.CreateModel(
            name='Transistors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Transition_Frequency', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Частота перехода')),
                ('Operating_Temperature', models.CharField(max_length=12, verbose_name='Рабочая температура')),
                ('Transistor_Type', models.CharField(max_length=50, verbose_name='Тип транзистора')),
                ('Collector_Cut_Off_Current', models.IntegerField(verbose_name='Ток отключения коллектора')),
                ('DC_Current_Gain', models.CharField(max_length=12, verbose_name='Усиление постоянного тока')),
                ('Collector_Current', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Ток коллектора')),
                ('Power_Dissipation', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Рассеиваемая мощность')),
                ('Collector_Emitter_Saturation_Voltage', models.CharField(max_length=50, verbose_name='Напряжение насыщения между коллектором и  эмиттером')),
                ('Collector_Emitter_Breakdown_Voltage', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Напряжение коллектора-эмиттера')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Транзистор',
                'verbose_name_plural': 'Транзисторы',
            },
        ),
        migrations.CreateModel(
            name='Resistors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Resistance', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Сопративление')),
                ('Power', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Мощность')),
                ('Type', models.CharField(max_length=50, verbose_name='Тип')),
                ('Tolerance', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Точность изготовления')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Резистор',
                'verbose_name_plural': 'Резисторы',
            },
        ),
        migrations.CreateModel(
            name='PCBComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_quantity', models.IntegerField(default=1, verbose_name='Необходимое количество')),
                ('pcb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pcb', verbose_name='Печатная плата')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uniquecomponent', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Состав платы',
                'verbose_name_plural': 'Составы плат',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Прочее',
                'verbose_name_plural': 'Прочее',
            },
        ),
        migrations.CreateModel(
            name='Diodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Forward_Voltage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Прямое напряжение (Vf@If)')),
                ('Reverse_Voltage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Обратное напряжение диода (Vr)')),
                ('Reverse_Recovery_Time', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Время восстановления диода (trr)')),
                ('Average_Rectified_Current', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Ток (Io)')),
                ('Diode_Configuration', models.CharField(max_length=100, verbose_name='Конфигурация сборки')),
                ('Reverse_Leakage_Current', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Обратный ток утечки (Ir)')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Диод',
                'verbose_name_plural': 'Диоды',
            },
        ),
        migrations.CreateModel(
            name='Capacitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Voltage_Rated', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Максимальное рабочее напряжение')),
                ('Equivalent_Series_Resistance', models.CharField(max_length=15, verbose_name='Эквивалентное последовательное сопротивление')),
                ('Tolerance', models.CharField(max_length=12, verbose_name='Точность изготовления')),
                ('Capacitance', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Емкость')),
                ('Temperature_Coefficient', models.CharField(max_length=10, verbose_name='Температурный коэффециент')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Конденсатор',
                'verbose_name_plural': 'Конденсаторы',
            },
        ),
    ]
