# Generated by Django 5.0.1 on 2024-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitors',
            name='Photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='diodes',
            name='Photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='resistors',
            name='Photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='transistors',
            name='Photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
    ]
