# Generated by Django 5.0.1 on 2024-02-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_capacitors_photo_alter_diodes_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitors',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='diodes',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='module',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='other',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='resistors',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
        migrations.AlterField(
            model_name='transistors',
            name='ID_COMPONENT',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента'),
        ),
    ]
