# Generated by Django 4.2.6 on 2023-11-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_pcb_elements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="element",
        ),
        migrations.RemoveField(
            model_name="module",
            name="element_quantity",
        ),
        migrations.RemoveField(
            model_name="module",
            name="pcb",
        ),
        migrations.CreateModel(
            name="ModuleComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_quantity",
                    models.IntegerField(
                        default=1, verbose_name="Необходимое количество элемента"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.element",
                        verbose_name="Элемент",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.module",
                        verbose_name="Модуль",
                    ),
                ),
                (
                    "pcb",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.pcb",
                        verbose_name="Печатная плата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав модуля",
                "verbose_name_plural": "Составы модулей",
            },
        ),
    ]
