# Generated by Django 4.2.6 on 2023-11-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_module_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modulecomposition",
            name="element",
        ),
        migrations.RemoveField(
            model_name="modulecomposition",
            name="element_quantity",
        ),
        migrations.AddField(
            model_name="modulecomposition",
            name="pcb_quantity",
            field=models.IntegerField(
                default=1, verbose_name="Необходимое количество платы"
            ),
        ),
        migrations.CreateModel(
            name="PCBComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_quantity",
                    models.IntegerField(
                        default=1, verbose_name="Необходимое количество элемента"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.element",
                        verbose_name="Элемент",
                    ),
                ),
                (
                    "pcb",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.pcb",
                        verbose_name="Печатная плата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав платы",
                "verbose_name_plural": "Составы плат",
            },
        ),
    ]
