# Generated by Django 4.2.6 on 2023-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_modulecomposition_element_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modulecomposition",
            name="pcb_quantity",
        ),
        migrations.RemoveField(
            model_name="pcbcomposition",
            name="element_quantity",
        ),
        migrations.AddField(
            model_name="modulecomposition",
            name="need_quantity",
            field=models.IntegerField(default=1, verbose_name="Необходимое количество"),
        ),
        migrations.AddField(
            model_name="pcbcomposition",
            name="need_quantity",
            field=models.IntegerField(default=1, verbose_name="Необходимое количество"),
        ),
    ]
