# Generated by Django 5.0.1 on 2024-02-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_modulecomposition_pcb_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='place',
            new_name='BOX',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='quantity',
            new_name='PCS',
        ),
        migrations.RenameField(
            model_name='pcb',
            old_name='place',
            new_name='BOX',
        ),
        migrations.RenameField(
            model_name='pcb',
            old_name='quantity',
            new_name='PCS',
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Transistors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Transition_Frequency', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Частота перехода')),
                ('Operating_Temperature', models.CharField(max_length=12, verbose_name='Рабочая температура')),
                ('Transistor_Type', models.CharField(max_length=50, verbose_name='Тип транзистора')),
                ('Collector_Cut_Off_Current', models.IntegerField(verbose_name='Ток отключения коллектора')),
                ('DC_Current_Gain', models.CharField(max_length=12, verbose_name='Усиление постоянного тока')),
                ('Collector_Current', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Ток коллектора')),
                ('Power_Dissipation', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Рассеиваемая мощность')),
                ('Collector_Emitter_Saturation_Voltage', models.CharField(max_length=50, verbose_name='Напряжение насыщения между коллектором и  эмиттером')),
                ('Collector_Emitter_Breakdown_Voltage', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Напряжение коллектора-эмиттера')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Транзистор',
                'verbose_name_plural': 'Транзисторы',
            },
        ),
        migrations.CreateModel(
            name='Resistors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Resistance', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Сопративление')),
                ('Power', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Мощность')),
                ('Type', models.CharField(max_length=50, verbose_name='Тип')),
                ('Tolerance', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Точность изготовления')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Резистор',
                'verbose_name_plural': 'Резисторы',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Прочее',
                'verbose_name_plural': 'Прочее',
            },
        ),
        migrations.CreateModel(
            name='Diodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Forward_Voltage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Прямое напряжение (Vf@If)')),
                ('Reverse_Voltage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Обратное напряжение диода (Vr)')),
                ('Reverse_Recovery_Time', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Время восстановления диода (trr)')),
                ('Average_Rectified_Current', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Ток (Io)')),
                ('Diode_Configuration', models.CharField(max_length=100, verbose_name='Конфигурация сборки')),
                ('Reverse_Leakage_Current', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Обратный ток утечки (Ir)')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Диод',
                'verbose_name_plural': 'Диоды',
            },
        ),
        migrations.CreateModel(
            name='Capacitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCS', models.IntegerField(default=0, null=True, verbose_name='Кол-во на складе')),
                ('BOX', models.TextField(verbose_name='Место')),
                ('MFR_PART_NUM', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер производителя')),
                ('Description', models.TextField(editable=False, null=True, verbose_name='Описание')),
                ('Photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('Package', models.CharField(max_length=100, verbose_name='Корпус компонента')),
                ('Voltage_Rated', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Максимальное рабочее напряжение')),
                ('Equivalent_Series_Resistance', models.CharField(max_length=15, verbose_name='Эквивалентное последовательное сопротивление')),
                ('Tolerance', models.CharField(max_length=12, verbose_name='Точность изготовления')),
                ('Capacitance', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Емкость')),
                ('Temperature_Coefficient', models.CharField(max_length=10, verbose_name='Температурный коэффециент')),
                ('category', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('ID_COMPONENT', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.uniquecomponent', verbose_name='Идентификатор компонента')),
            ],
            options={
                'verbose_name': 'Конденсатор',
                'verbose_name_plural': 'Конденсаторы',
            },
        ),
        migrations.AlterField(
            model_name='pcbcomposition',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uniquecomponent', verbose_name='Элемент'),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
