# Generated by Django 5.0.1 on 2024-02-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_uniquecomponent_rename_place_module_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='Description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
