# Generated by Django 5.0.1 on 2024-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_other_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='stepFile',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
