# Generated by Django 5.0.1 on 2024-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_module_stepfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcb',
            name='assembly_drawing',
            field=models.FileField(null=True, upload_to='images/<django.db.models.fields.CharField>', verbose_name='Сборный чертеж'),
        ),
        migrations.AddField(
            model_name='pcb',
            name='electrical_diagram',
            field=models.FileField(null=True, upload_to='images/<django.db.models.fields.CharField>', verbose_name='Электрическая схема'),
        ),
        migrations.AddField(
            model_name='pcb',
            name='list_components',
            field=models.FileField(null=True, upload_to='images/<django.db.models.fields.CharField>', verbose_name='Перечень компонентов'),
        ),
        migrations.AlterField(
            model_name='module',
            name='stepFile',
            field=models.FileField(null=True, upload_to='files', verbose_name='3д модель'),
        ),
    ]
