# Generated by Django 5.0.1 on 2024-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pcb_assembly_drawing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/gerber', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Гербер файл',
                'verbose_name_plural': 'Гербер файлы',
            },
        ),
        migrations.AddField(
            model_name='pcb',
            name='gerber_files',
            field=models.ManyToManyField(blank=True, null=True, to='main.gerber', verbose_name='Гербер файлы'),
        ),
    ]
